#!/usr/bin/env ruby

home = File.expand_path('.')
name = ARGV.empty? ? File.basename(home) : ARGV[0]

require File.join(home, 'lib/wab/version')

`script/build-export`

version = WAB::VERSION

def log(str, dash = '-')
  puts "\n#{str}"
  puts dash * str.to_s.length
end

log "Releasing #{name} - #{version}", '='

tags = `git tag`.split("\n")
tag = "v#{version}"
unless tags.include?(tag)
  log "tagging with #{tag}.."
  `git tag -m "release #{version}" v#{version}`
  puts "  tag '#{tag}' created."
  puts "  pushing '#{tag}' to remote..\n\n"
  `git push --tags`
end

log 'Building gem..'
out = `gem build #{name}.gemspec`
out.include?('Success') ? puts(out) : exit(0)

log "pushing #{name}-#{version}.gem.."
out = `gem push #{name}-#{version}.gem`
puts out
