#!/usr/bin/env ruby
# encoding: UTF-8

require 'fileutils'

def path_to(*subdirs)
  File.expand_path(File.join('..', *subdirs), __dir__)
end

def dest_dir(*contents)
  path_to('view', 'pages', 'assets', *contents)
end

def js_src_dir
  path_to('view', 'js')
end

def success_message(file)
  path = file.sub("#{Dir.pwd}/", '')
  puts "#{'Generated'.rjust(15)}: #{path}"
end

def generate_css
  src  ||= path_to('view', 'styles', 'wab.scss')
  dest ||= dest_dir('css', 'wab.css')

  FileUtils.mkdir_p dest_dir('css')
  `sass #{src} #{dest} --style compressed`
  success_message(dest)
end

def generate_js
  minified = ARGV.include?('-m') ? '--minified ' : ''
  dest = "#{dest_dir('js')}/wab.js"
  out = `#{path_to('node_modules', '.bin', 'babel')} #{minified}-o #{dest} #{js_src_dir}/wab.js #{js_src_dir}/list.js #{js_src_dir}/obj.js #{js_src_dir}/view.js`
  if out.empty?
    success_message(dest)
  else
    puts out
  end
end

begin
  require 'sass'
  generate_css
  generate_js
rescue LoadError
  puts "\n'sass' gem not found. Installing.."
  puts `gem install sass --no-ri --no-rdoc`
  puts ''
  generate_css
end
