#!/usr/bin/env ruby
# encoding: UTF-8

def compact_js(src, df)
  cnt = 0
  sf = File.new(src)
  sf.each_line do |line|
    cnt += 1
    line.strip!
    # Remove comments from all but the two header lines.
    if 2 < cnt
      line = remove_js_comment(line)
      line = compact_js_line(line)
    end
    df.puts(line) unless 0 == line.length
  end
end

def remove_js_comment(line)
  quote = nil
  slash = 0
  i = 0
  line.each_char { |c|
    i += 1
    if quote.nil?
      if '"' == c || '\'' == c
        quote = c
      elsif '/' == c
        slash += 1
        if 2 <= slash
          return line[0,i - 2]
        end
      else
        slash = 0
      end
    else
      if c == quote
        quote = nil
      end
    end
  }
  line
end

$punc = '(){}[]/*-+=|&%^:;<>?,'

def compact_js_line(line)
  quote = nil
  space = false
  past_punc = false
  new_line = ''
  line.each_char { |c|
    if quote.nil?
      if '"' == c || '\'' == c
        quote = c
        past_punc = false
        new_line += c
      elsif ' ' == c || '\t' == c
        space = !past_punc
        past_punc = false
      else
        if $punc.include?(c)
          past_punc = true
          space = false
          # TBD if an alphanum then put in space if needed
          # if /+=-{()} then drop space
        else
          past_punc = false
          if space
            new_line += ' '
            space = false
          end
        end
        new_line += c
      end
    else
      if c == quote
        quote = nil
      end
      new_line += c
    end
  }
  new_line
end

$here = __dir__
$pages = File.join(__dir__, 'pages')

begin
  `mkdir -p #{File.join(__dir__, 'pages', 'assets', 'js')}`
  df = File.open(File.join($pages, 'assets', 'js', 'wab.js'), 'w')
  compact_js(File.join(__dir__, 'js', 'wab.js'), df)
  compact_js(File.join(__dir__, 'js', 'view.js'), df)
  compact_js(File.join(__dir__, 'js', 'objlist.js'), df)
  compact_js(File.join(__dir__, 'js', 'obj.js'), df)
rescue Exception => e
  puts "#{e.class}: #{e.message}"
  e.backtrace.each { |line| puts line }
end
